# Generated by Django 5.2 on 2025-04-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_create_shortlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Уникальный слаг",
            ),
        ),
        migrations.DeleteModel(
            name="ShortLink",
        ),
    ]
