# Generated by Django 5.2 on 2025-04-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_slug_delete_shortlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="slug",
        ),
        migrations.AddField(
            model_name="recipe",
            name="urn",
            field=models.SlugField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Уникальный идентификатор",
            ),
        ),
    ]
