# Generated by Django 5.2 on 2025-05-12 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_component_options_alter_favorite_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Время готовки (мин)",
            ),
        ),
    ]
