# Generated by Django 5.2 on 2025-05-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "default_related_name": "shopping_carts",
                "verbose_name": "Список покупок",
                "verbose_name_plural": "Списки покупок",
            },
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="urn",
        ),
    ]
