# Generated by Django 5.2 on 2025-05-12 12:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_subscription_subscribed_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodgramuser",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^[\\w.@+-]+\\Z")
                ],
                verbose_name="Никнейм",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscribed_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписан на",
            ),
        ),
    ]
